spring.application.name=DemoTeacher

spring.datasource.url=jdbc:postgresql://aws-1-ca-central-1.pooler.supabase.com:5432/postgres?user=postgres.oustfrcvaoycxntlmyse&password=Amruta@182002
spring.datasource.drive-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true